config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
      :registrations => 'users/registrations',
      :omniauth_callbacks => "omniauth_callbacks"
    }

  root 'feeds#index'

  get '/show', to: 'feeds#show', as: 'show'

  resources :feeds do
    resources :posts, except: [:index]
  end
  resources :profiles do
    resources :posts, except: [:index]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  has_many :posts, dependent: :destroy
  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, except: [:index, :new, :create]

  def index
    @profiles = Profile.all
  end

  def show
    @posts = @profile.posts
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      flash[:success] = 'Profile Created Successfully!'
      redirect_to profile_path(@profile)
    else
      flash[:error] = 'Something Went Wrong!'
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      flash[:success] = 'Profile Updated Successfully!'
      redirect_to profile_path(@profile)
    else
      flash[:error] = 'Something Went Wrong!'
      render :edit
    end
  end

  def destroy
    @profile.destroy
    flash[:success] = 'Profile Deleted Successfully!'
    redirect_to profiles_path
  end

  private
  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :email, :language, :experience, :bio, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <div class='col m6'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %>
  </div>
  <div class='col m6'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>
  <div class='col m6'>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class='input-field col m6'>
   <%= f.label :language %>
     <br />
     <br />
   <%= f.select :language, ['Ruby on Rails', 'HTML/CSS', 'JavaScript', 'PHP', 'Python', 'Java', 'Cake', 'ReactJS'] %>
 </div>
  <div class='col m6'>
    <%= f.label :experience %>
      <br />
      <br />
    <%= f.select :experience, ['> 1 year', '1-2 years', '3 years', '4 years', '5+ years'] %>
  </div>
  <div class='col m6'>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <div class='col m6'>
    <%= f.label :avatar %>
    <%= f.attachinary_file_field :avatar %>
  </div>
  <div class='center'>
    <%= f.submit nil, class: 'btn form-button' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit: <%= @profile.first_name %></h1>
<hr>
<%= render(partial: 'form') %>

app/views/profiles/index.html.erb
<h1>Find Other Developers</h1>
<hr>
<% if @profiles.any? %>
<ul class="collection container border">
  <% @profiles.each do |profile| %>
  <li class="collection-item avatar">
    <div class='row'>
      <% if profile.avatar? %>
        <div class='col s12 m3'>
          <%= cl_image_tag(profile.avatar.path, {size: '100x100', crop: :thumb}) %>
        </div>
      <% end %>
      <div class='col s12 m8'>
        <span class="title"><%= link_to "#{profile.first_name} #{profile.last_name}", profile_path(profile) %></span>
        <p><%= profile.language %> <br>
           <%= truncate(profile.bio, length: 30) %>
        </p>
      </div>
    </div>
  </li>
  <% end %>
</ul>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<hr>
<%= render(partial: 'form') %>

app/views/profiles/show.html.erb
<h1 class='center'><%= @profile.full_name %></h1>
<hr>

<div>
  <div class="leftfloat1">
    <% if @profile.avatar? %>
      <%= cl_image_tag(@profile.avatar.path, { size: '250x250', crop: :fit }) %>
    <% end %>
    <br><br>
    <%= link_to "Edit Profile", edit_profile_path(@profile), class: "btn blue" %>
    <br><br>
  </div>
  <div class="leftfloat2">
    <h4>Language: <small><%= @profile.language %></small></h4>
    <h4>Experience: <small><%= @profile.experience %></small></h4>
    <h4>Bio: <small><%= @profile.bio %></small></h4>
  </div>
</div>
<br>

<hr class='clearfloat'>
<div class='center'>
  <%= link_to "New Post", new_profile_post_path(@profile), class: 'btn blue' %>
  <h2>Recent Posts</h2>
</div>
<br>
<% if @posts.try(:any?) %>
  <div class="row">
    <% @posts.order('created_at DESC').each do |post| %>
       <div class="col s12 ">
         <div class="card grey darken-3">
           <div class="card-content white-text">
             <p class="right"><%= post.created_at.strftime("%b %e at %l:%M %p") %></p>
             <br>
             <span class="card-title"><%= post.title %></span>

             <small style="color:yellow;"> -  <%= post.category %></small>
             <p><%= post.body %></p>
           </div>
           <% if current_user.id == @profile.user_id %>
             <div class="card-action center">
               <%= link_to "Edit", edit_profile_post_path(@profile, post), class: 'btn blue darken-2' %>
               <%= link_to "Delete", profile_post_path(@profile, post), class: 'btn red darken-3', method: :delete, data: {confirm: 'Really Delete?'}%>
             </div>
           <% end %>
         </div>
       </div>
    <% end %>
   </div>
 <% end %>
<hr>