config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
      :registrations => 'users/registrations',
      :omniauth_callbacks => "omniauth_callbacks"
    }

  root 'feeds#index'

  get '/show', to: 'feeds#show', as: 'show'

  resources :feeds do
    resources :posts, except: [:index]
  end
  resources :profiles do
    resources :posts, except: [:index]
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :posts
  belongs_to :user
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show]

  def index
    @feeds = Feed.all
    @profile = Profile.all
  end

  def show
    @posts = @feed.posts
  end

  private
    def feed_params
      params.require(:feed).permit(:category, :user_id)
    end

    def set_feed
      @feed = Feed.find(params[:id])
    end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/feeds/index.html.erb
<h1 class='center'>Welcome</h1>
<% if @profile.any? %>
  <h1 class='center'>Hackers-R-Us</h1>
  <p class='center teal-text'><strong>Welcome to the best place to meet people like you. We love to hack and connect. Feel free to explore this place and connect to the web of internet peoples.</strong></p>
  <% @feeds.all %>
  <ul>
    <% @feeds.each do |feed| %>
      <li>
        <%= link_to feed.category, feed_path(feed) %>
      </li>
    <% end %>
 </ul>
<% else %>
  <div class='center'>
    <h1>You have not made a profile yet!</h1>
    <h3><%= link_to 'Make Your Profile', new_profile_path, class:'teal-text'%></h3>
  </div>
<% end %>

app/views/feeds/show.html.erb
<h1 class='center'>Posts for: <%= @feed.category %></h1>
<hr />

<% @posts.each do |p| %>



  <div class="row">
        <div class="col s12">
          <div class="card grey darken-3">
            <div class="card-content white-text">
              <p class="right"><%= p.created_at.strftime("%b %e at %l:%M %p") %></p>
              <br />
              <span class="card-title"><%= p.title %></span>
              <small style="color:yellow;"> - <%= p.category %></small>
              <p><%= p.body %></p>

            </div>
          </div>
        </div>
      </div>
<% end %>