config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
      :registrations => 'users/registrations',
      :omniauth_callbacks => "omniauth_callbacks"
    }

  root 'feeds#index'

  get '/show', to: 'feeds#show', as: 'show'

  resources :feeds do
    resources :posts, except: [:index]
  end
  resources :profiles do
    resources :posts, except: [:index]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  belongs_to :user
  belongs_to :feed, optional: true


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_profile
  before_action :set_post, except: [:new, :create]

  def show
    paginate(page: params[:page], per_page: 15)
  end

  def new
    @post = @profile.posts.new
  end

  def create
    @post = @profile.posts.new(post_params)
    @post.feed_id = Feed.find_by(category: @post.category).try(:id)
    if @post.save
      redirect_to profile_path(@profile), success: 'Your post was added!'
    else
      render :new, error: 'Something went wrong, try again!'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to profile_path(@profile), success: 'Your post was edited!'
    else
      render :edit, error: 'Something went wrong, try again!'
    end
  end

  def destroy
    @post.destroy
    redirect_to profile_path(@profile)
  end

  private
    def set_post
      @post = @profile.posts.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    def post_params
      params.require(:post).permit(:title, :category, :body, :feed_id, :profile_id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@profile, @post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :category %>
  <br />
  <br />
  <%= f.select :category, ['Ruby on Rails', 'HTML/CSS', 'JavaScript', 'PHP', 'Python', 'Java', 'Cake', 'ReactJS'] %>
  <br />
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br />
  <%= f.submit nil, class: 'btn' %>
<% end %>

app/views/posts/edit.html.erb
<h1> You are editing post: <%= @post.title %>
<hr />

<%= render(partial: 'form') %>

app/views/posts/new.html.erb
<h1> You are creating a new post!<h1>
<hr />

<%= render(partial: 'form') %>

app/views/posts/show.html.erb
<h1>Your Posts</h1>
<hr />

<div>
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <div class=''
        <h6><%= post.title %></h6>
        <div>
          <%= link_to 'Show', post_path(post), class: 'btn' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>You have no posts, please create one.</h3>
  <% end %>
</div>
<div class='clearfix'></div>
<hr />
  <div class='well'>
    <%= will_paginate @posts %>
  </div>
<hr />
<%= link_to 'New Post', new_post_path, class: 'btn' %>