config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
      :registrations => 'users/registrations',
      :omniauth_callbacks => "omniauth_callbacks"
    }

  root 'feeds#index'

  get '/show', to: 'feeds#show', as: 'show'

  resources :feeds do
    resources :posts, except: [:index]
  end
  resources :profiles do
    resources :posts, except: [:index]
  end
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper teal accent-3">
    <a href="/" class="brand-logo" id='lable'>Hackers-R-Us</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <!-- <li> <%= link_to 'About', feeds_path %> </li> -->
      <li> <%= link_to 'Feeds', feeds_path %> </li>
      <% if user_signed_in? %>
        <li><%= link_to "Browse", profiles_path %>
        <li><%= link_to "Profile", profile_path(current_user) %>
        <li><%= link_to 'Account', edit_user_registration_path %>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <!-- <li> <%= link_to 'About', feeds_path %> </li> -->
      <li> <%= link_to 'Feeds', feeds_path %> </li>
      <% if user_signed_in? %>
        <li><%= link_to "Profile", profile_path(current_user) %>
        <li><%= link_to 'Account', edit_user_registration_path %>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body class='purple lighten-5'>
    <%= render(partial: 'layouts/navbar') %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
    <main>
      <div class='container'>
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer teal accent-3">
      <div class="container">
        <div class="row">
          <div class="col l4 offset-l2 s12">
            <ul>
              <li class="grey-text text-lighten-4">Copyright (c) 2016 Hackers-R-Us All Rights Reserved.</li>
            </ul>
          </div>
          <div class="col l4 offset-l2 s12">
            <ul class="white-text">
              <li><a class="grey-text text-lighten-4" href="#!">Link 1</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>